create table "public"."Coach" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "email" text
);


alter table "public"."Coach" enable row level security;

create table "public"."Lesson type" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "type" text,
    "coach_busy_level" text,
    "coaches" bigint
);


alter table "public"."Lesson type" enable row level security;

create table "public"."Lesson" (
    "id" bigint generated by default as identity not null,
    "lesson_type" bigint,
    "participants" bigint,
    "date" date,
    "start_time" time without time zone,
    "end_time" time without time zone
);


alter table "public"."Lesson" enable row level security;

create table "public"."Participant" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "email" text
);


alter table "public"."Participant" enable row level security;

CREATE UNIQUE INDEX "Coach_id_key" ON public."Coach" USING btree (id);

CREATE UNIQUE INDEX "Coach_pkey" ON public."Coach" USING btree (id);

CREATE UNIQUE INDEX "Lesson type_pkey" ON public."Lesson type" USING btree (id);

CREATE UNIQUE INDEX "Lesson_pkey" ON public."Lesson" USING btree (id);

CREATE UNIQUE INDEX "Participant_pkey" ON public."Participant" USING btree (id);

alter table "public"."Coach" add constraint "Coach_pkey" PRIMARY KEY using index "Coach_pkey";

alter table "public"."Lesson type" add constraint "Lesson type_pkey" PRIMARY KEY using index "Lesson type_pkey";

alter table "public"."Lesson" add constraint "Lesson_pkey" PRIMARY KEY using index "Lesson_pkey";

alter table "public"."Participant" add constraint "Participant_pkey" PRIMARY KEY using index "Participant_pkey";

alter table "public"."Coach" add constraint "Coach_id_key" UNIQUE using index "Coach_id_key";

alter table "public"."Lesson type" add constraint "Lesson type_coaches_fkey" FOREIGN KEY (coaches) REFERENCES "Coach"(id) not valid;

alter table "public"."Lesson type" validate constraint "Lesson type_coaches_fkey";

alter table "public"."Lesson" add constraint "Lesson_lesson_type_fkey" FOREIGN KEY (lesson_type) REFERENCES "Lesson type"(id) not valid;

alter table "public"."Lesson" validate constraint "Lesson_lesson_type_fkey";

alter table "public"."Lesson" add constraint "Lesson_participants_fkey" FOREIGN KEY (participants) REFERENCES "Participant"(id) not valid;

alter table "public"."Lesson" validate constraint "Lesson_participants_fkey";


